"""Vision scenario tests against the deployed Cloud Run service.

Sends real kitchen images + text through the WebSocket and verifies that
Gemini's responses contain relevant visual observations and appropriate
tool calls.  Uses the real Gemini API (no fakes).

Requires:
  GEMINI_API_KEY  — set in environment
  DEPLOYED_URL    — Cloud Run service URL (defaults to production)
  harness/fixtures/images/*.jpg — generated by scripts/generate_test_images.py
"""

import os

import pytest
import websockets

from tests.live.conftest import (
    ws_url, setup_message, image_message, text_message,
    collect_events, extract_output_transcription, extract_tool_calls,
    extract_tool_names, extract_audio_chunks,
    assert_any_keyword, assert_no_forbidden,
    ssl_context,
)

pytestmark = [
    pytest.mark.skipif(
        not os.environ.get("GEMINI_API_KEY"),
        reason="GEMINI_API_KEY not set",
    ),
    pytest.mark.timeout(60),
]


class TestVisionScenarios:
    """Send real kitchen images and verify agent vision."""

    @pytest.mark.asyncio
    async def test_ingredient_recognition(self):
        """Send ingredient image + ask what agent sees."""
        async with websockets.connect(
            ws_url("vision_ingredients"), ssl=ssl_context(),
            open_timeout=15, close_timeout=5,
        ) as ws:
            await ws.send(setup_message())
            await ws.send(image_message("garlic_butter_ingredients.jpg"))
            await ws.send(text_message(
                "Chef, what ingredients do you see in front of me?"
            ))

            events = await collect_events(ws, timeout_s=35)
            transcript = extract_output_transcription(events)
            audio = extract_audio_chunks(events)

            assert len(audio) > 0, "Expected audio response"
            assert len(transcript) > 0, f"No transcription received. Events: {events[:5]}"
            assert_no_forbidden(transcript)

    @pytest.mark.asyncio
    async def test_recipe_initiation_with_image(self):
        """Send ingredient image + cooking request, expect update_recipe tool call."""
        async with websockets.connect(
            ws_url("vision_recipe"), ssl=ssl_context(),
            open_timeout=15, close_timeout=5,
        ) as ws:
            await ws.send(setup_message())
            await ws.send(image_message("garlic_butter_ingredients.jpg"))
            await ws.send(text_message(
                "Let's cook something with what you see. I'm ready to start."
            ))

            events = await collect_events(ws, timeout_s=40)
            tool_calls = extract_tool_calls(events)
            transcript = extract_output_transcription(events)

            has_recipe_tool = any(tc["name"] == "update_recipe" for tc in tool_calls)
            has_step_tool = any(tc["name"] == "update_cooking_step" for tc in tool_calls)

            assert has_recipe_tool or has_step_tool or len(transcript) > 10, (
                f"Expected update_recipe/update_cooking_step tool call or substantial "
                f"response. Tool calls: {[tc['name'] for tc in tool_calls]}, "
                f"transcript: {transcript[:200]}"
            )

    @pytest.mark.asyncio
    async def test_cold_pan_warning(self):
        """Send cold pan image and ask if ready to cook — agent should warn."""
        async with websockets.connect(
            ws_url("vision_cold_pan"), ssl=ssl_context(),
            open_timeout=15, close_timeout=5,
        ) as ws:
            await ws.send(setup_message())
            await ws.send(image_message("cold_pan_oil.jpg"))
            await ws.send(text_message(
                "The pan has oil in it. Ready to put the chicken in?"
            ))

            events = await collect_events(ws, timeout_s=35)
            transcript = extract_output_transcription(events)

            assert len(transcript) > 0, "No transcription received"
            assert_no_forbidden(transcript)

    @pytest.mark.asyncio
    async def test_sear_recognition(self):
        """Send searing chicken image and ask about progress."""
        async with websockets.connect(
            ws_url("vision_sear"), ssl=ssl_context(),
            open_timeout=15, close_timeout=5,
        ) as ws:
            await ws.send(setup_message())
            await ws.send(text_message(
                "We're making garlic butter chicken thighs. The chicken is searing now."
            ))
            events1 = await collect_events(ws, timeout_s=30)

            await ws.send(image_message("chicken_searing.jpg"))
            await ws.send(text_message("How does the sear look?"))

            events2 = await collect_events(ws, timeout_s=35)
            transcript = extract_output_transcription(events2)

            assert len(transcript) > 0, "No transcription for sear assessment"
            assert_no_forbidden(transcript)

    @pytest.mark.asyncio
    async def test_burnt_food_detection(self):
        """Send burnt food image and ask if it's okay — agent should respond."""
        async with websockets.connect(
            ws_url("vision_burnt"), ssl=ssl_context(),
            open_timeout=15, close_timeout=5,
        ) as ws:
            await ws.send(setup_message())
            await ws.send(image_message("burnt_food.jpg"))
            await ws.send(text_message("Is this looking okay or is it overdone?"))

            events = await collect_events(ws, timeout_s=35)
            transcript = extract_output_transcription(events)
            audio = extract_audio_chunks(events)

            # Agent may respond with audio but not always produce
            # a transcription in time.
            assert len(audio) > 0 or len(transcript) > 0, (
                "No audio or transcription received"
            )
            if transcript:
                assert_no_forbidden(transcript)

    @pytest.mark.asyncio
    async def test_golden_sear_positive_assessment(self):
        """Send golden-brown sear image — agent should give positive feedback."""
        async with websockets.connect(
            ws_url("vision_golden"), ssl=ssl_context(),
            open_timeout=15, close_timeout=5,
        ) as ws:
            await ws.send(setup_message())
            await ws.send(text_message(
                "I'm pan-searing chicken thighs. Just flipped them."
            ))
            await collect_events(ws, timeout_s=30)

            await ws.send(image_message("golden_brown_sear.jpg"))
            await ws.send(text_message("How does this side look?"))

            events = await collect_events(ws, timeout_s=35)
            transcript = extract_output_transcription(events)

            assert len(transcript) > 0, "No transcription received"
            assert_no_forbidden(transcript)
